name: 'Setup superDoit'
description: 'Setup superDoit for running GemStone Smalltalk scripts: .stone, .solo, and .topaz'
author: 'Dale Henrichs, GemTalk Systems'
inputs:
  gemstone-version:
    description: 'Version of GemStone to use when running scripts'
  superDoit-source:
    description: 'GigHub slug of the superDoit source repository'
    required: false
    default: 'dalehenrich/superDoit'
  superDoit-branch:
    description: 'Branch or tag to use from superDoit repository'
    required: false
    default: 'masterV1.0'
outputs:
  gemstone-version:
    description: 'GemStone version selection'
  gemstone-product-directory:
    description: 'directory where GemStone product tree should be installed'
  gemstone-product-name:
    description: 'name of GemStone product tree directory'
runs:
  using: "composite"
  steps:
    - run: |
        export superDoit_source=${{ inputs.superDoit-source }}
        export superDoit_branch=${{ inputs.superDoit-branch }}
        superDoit_gemstone_version=`./.github/actions/downloadSuperDoit.sh`
        echo "OUTPUT=:$superDoit_gemstone_version"
        echo "::set-output name=gemstone-version::$superDoit_gemstone_version"
      shell: bash

