name: 'Setup superDoit'
description: 'Setup superDoit for running GemStone Smalltalk scripts: .stone, .solo, and .topaz'
author: 'Dale Henrichs, GemTalk Systems'
inputs:
  gemstone-version:
    description: 'Version of GemStone to use when running scripts'
  superDoit-source:
    description: 'GigHub slug of the superDoit source repository'
    required: false
    default: 'dalehenrich/superDoit'
  superDoit-branch:
    description: 'Branch or tag to use from superDoit repository'
    required: false
    default: 'v2'
outputs:
  gemstone-version:
    description: 'GemStone version used for stones'
    value: ${{ steps.downloadSuperDoitProject.outputs.gemstone-version }}
  gemstone-product-path:
    description: 'path to requested gemstone-version product tree. Suitable for use as GEMSTONE env var'
    value: ${{ steps.downloadGemStoneProductTree.outputs.gemstone-product-path }}
  gemstone-product-name:
    description: 'name of GemStone product tree directory'
    value: ${{steps.downloadGemStoneProductTree.outputs.gemstone-product-name}}
  superDoit-root:
    description: 'root directory of the downloaded superDoit project'
    value: ${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}
runs:
  using: "composite"
  steps:
    - id: downloadSuperDoitProject
      run: |
        export superDoit_gemstone_version=${{ inputs.gemstone-version }}
        echo "gemstone-version=$superDoit_gemstone_version" >> $GITHUB_OUTPUT
        export superDoit_source=${{ inputs.superDoit-source }}
        export superDoit_branch=${{ inputs.superDoit-branch }}
        ${{ github.action_path }}/.github/actions/downloadSuperDoitProject.sh
      shell: bash
    - id: downloadGemStoneProductTree
      run: |
        export superDoit_gemstone_version=${{ inputs.gemstone-version }}
        export superDoit_root_dir=${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}
        ${{ github.action_path }}/.github/actions/downloadGemStoneProductTree.sh
      shell: bash
    - id: setup_shared_memory_on_mac
      run: |
        case "$PLATFORM" in macos*)
          echo "-- set up shared memory on Mac"
          ${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}/dev/setSharedMemory.sh
        esac
      shell: bash
