name: 'Setup superDoit'
description: 'Setup superDoit for running GemStone Smalltalk scripts: .stone, .solo, and .topaz'
author: 'Dale Henrichs, GemTalk Systems'
inputs:
  gemstone-version:
    description: 'Version of GemStone to use when running scripts'
  superDoit-source:
    description: 'GigHub slug of the superDoit source repository'
    required: false
    default: 'dalehenrich/superDoit'
  superDoit-branch:
    description: 'Branch or tag to use from superDoit repository'
    required: false
    default: 'masterV1.0'
outputs:
  gemstone-version:
    description: 'GemStone version selection'
  gemstone-product-directory:
    description: 'directory where GemStone product tree should be installed'
  gemstone-product-name:
    description: 'name of GemStone product tree directory'
runs:
  using: "composite"
  steps:
    - id: downloadSuperDoit
      uses: ./.github/actions/setup-superDoit_js
        uses: ./
        with:
          gemstone-version: ${{matrix.gemstone}}
          superDoit-branch: 'v2.0.0-issue_24'
    - run: echo product-version ${{ steps.downloadSuperDoit.outputs.gemstone-version }} product-directory ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
      shell: bash
    # download product tree for mac
    - name: download_gemstone_for_mac
      if: ${{ matrix.os == 'macos-10.15' }}
      run: |
        cd ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
        downloadGemStone.sh ${{ matrix.gemstone }}
   # create symbolic link for mac solo scripts to product tree for 3.6.0 and 3.6.1
    - name: create_solo_symbolic_link_for_mac
      if: ${{ (matrix.os == 'macos-10.15') && ( ( matrix.gemstone =='3.6.0') || ( matrix.gemstone == '3.6.1') ) }}
      run: |
        cd ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
        ln -s ${{steps.downloadSuperDoit.outputs.gemstone-product-directory}}/${{ steps.downloadSuperDoit.outputs.gemstone-product-name }} ../solo/product

    - run: |
        simple.solo -h
        simple.solo
        versionReport.solo

