name: 'Setup superDoit'
description: 'Setup superDoit for running GemStone Smalltalk scripts: .stone, .solo, and .topaz'
author: 'Dale Henrichs, GemTalk Systems'
inputs:
  gemstone-version:
    description: 'Version of GemStone to use when running scripts'
  superDoit-source:
    description: 'GigHub slug of the superDoit source repository'
    required: false
    default: 'dalehenrich/superDoit'
  superDoit-branch:
    description: 'Branch or tag to use from superDoit repository'
    required: false
    default: 'v2'
outputs:
  gemstone-version:
    description: 'GemStone version used for stones'
    value: ${{ steps.downloadSuperDoitProject.outputs.gemstone-version }}
  gemstone-product-path:
    description: 'path to requested gemstone-version product tree. Suitable for use as GEMSTONE env var'
  gemstone-product-directory:
    description: 'directory where GemStone product tree should be installed'
  gemstone-product-name:
    description: 'name of GemStone product tree directory'
  solo-extent-version:
    description: 'GemStone version used for solo'
  solo-product-name:
    description: 'name of GemStone product tree directory used for solo'
  installation-directory:
    description: 'path to the superDoit project installation'
runs:
  using: "composite"
  steps:
    - id: downloadSuperDoitProject
      run: |
        export superDoit_gemstone_version=${{ inputs.gemstone-version }}
        echo "::set-output name=gemstone-version::$superDoit_gemstone_version"
        export superDoit_source=${{ inputs.superDoit-source }}
        export superDoit_branch=${{ inputs.superDoit-branch }}
        ./.github/actions/downloadSuperDoitProject.sh
        echo "superDoit installation directory: ${{ outputs.installation-directory }}"
      shell: bash

