name: 'Setup superDoit'
description: 'Setup superDoit for running GemStone Smalltalk scripts: .stone, .solo, and .topaz'
author: 'Dale Henrichs, GemTalk Systems'
inputs:
  gemstone-version:
    description: 'Version of GemStone to use when running scripts'
  superDoit-source:
    description: 'GigHub slug of the superDoit source repository'
    required: false
    default: 'dalehenrich/superDoit'
  superDoit-branch:
    description: 'Branch or tag to use from superDoit repository'
    required: false
    default: 'masterV1.0'
outputs:
  gemstone-version:
    description: 'GemStone version selection'
  gemstone-product-directory:
    description: 'directory where GemStone product tree should be installed'
  gemstone-product-name:
    description: 'name of GemStone product tree directory'
  solo-extent-version:
    description: 'GemStone version used for solo'
  solo-product-name:
    description: 'name of GemStone product tree directory used for solo'
runs:
  using: 'node12'
  main: 'dist/index.js'
