name: 'Setup superDoit'
description: 'Setup superDoit for running GemStone Smalltalk scripts: .stone, .solo, and .topaz'
author: 'Dale Henrichs, GemTalk Systems'
inputs:
  gemstone-version:
    description: 'Version of GemStone to use when running scripts'
  superDoit-source:
    description: 'GigHub slug of the superDoit source repository'
    required: false
    default: 'dalehenrich/superDoit'
  superDoit-branch:
    description: 'Branch or tag to use from superDoit repository'
    required: false
    default: 'v2'
outputs:
  gemstone-version:
    description: 'GemStone version used for stones'
    value: ${{ steps.downloadSuperDoitProject.outputs.gemstone-version }}
  gemstone-product-path:
    description: 'path to requested gemstone-version product tree. Suitable for use as GEMSTONE env var'
    value: ${{ steps.downloadGemStoneProductTree.outputs.gemstone-product-path }}
  gemstone-product-name:
    description: 'name of GemStone product tree directory'
    value: ${{steps.downloadGemStoneProductTree.outputs.gemstone-product-name}}
  stone-directory:
    description: 'directory where stone is running'
    value: ${{steps.setup_and_start_stone.outputs.stone-directory}}
  topazini-path:
    description: 'location of the default .topazini file'
    value: ${{steps.setup_and_start_stone.outputs.topazini-path}}
  stone-name:
    description: 'name of the stone'
    value: ${{steps.setup_and_start_stone.outputs.stone-name}}
  stone-system-conf-path:
    description: 'path to sysmtem.conf file'
    value: ${{steps.setup_and_start_stone.outputs.stone-system-conf-path}}
  solo-extent-version:
    description: 'GemStone version used for solo'
    value: ${{ steps.downloadSoloExtent.outputs.solo-extent-version }}
  solo-product-name:
    description: 'name of GemStone product tree directory used for solo'
    value: ${{steps.setup_and_start_stone.outputs.stone-name}}
  superDoit-root:
    description: 'root directory of the downloaded superDoit project'
    value: ${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}
runs:
  using: "composite"
  steps:
    - id: downloadSuperDoitProject
      run: |
        export superDoit_gemstone_version=${{ inputs.gemstone-version }}
        echo "::set-output name=gemstone-version::$superDoit_gemstone_version"
        export superDoit_source=${{ inputs.superDoit-source }}
        export superDoit_branch=${{ inputs.superDoit-branch }}
        ${{ github.action_path }}/.github/actions/downloadSuperDoitProject.sh
      shell: bash
    - id: downloadSoloExtent
      run: |
        export superDoit_gemstone_version=${{ inputs.gemstone-version }}
        export superDoit_root_dir=${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}
        ${{ github.action_path }}/.github/actions/downloadSoloExtent.sh
      shell: bash
    - id: downloadGemStoneProductTree
      run: |
        export superDoit_gemstone_version=${{ inputs.gemstone-version }}
        export superDoit_root_dir=${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}
        export superDoit_solo_extent_version=${{ steps.downloadSoloExtent.outputs.solo-extent-version }}
        ${{ github.action_path }}/.github/actions/downloadGemStoneProductTree.sh
      shell: bash
    - id: setup_shared_memory_on_mac
      run: |
        if [ "$PLATFORM" = "macos-10.15" ] ; then
          echo "-- set up shared memory on Mac"
          ${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}/dev/setSharedMemory.sh
        fi
      shell: bash
    - id: setup_and_start_stone
      run: |
        export GEMSTONE=${{ steps.downloadGemStoneProductTree.outputs.gemstone-product-path }}
        export GEMSTONE_VERSION=${{ steps.downloadSuperDoitProject.outputs.gemstone-version }}
        export GEMSTONE_STONE_NAME=gs_$GEMSTONE_VERSION
        echo "::set-output name=stone-name::$GEMSTONE_STONE_NAME"
        export GEMSTONE_STONE_DIR=${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}/gemstone/stones/$GEMSTONE_STONE_NAME
        echo "::set-output name=stone-directory::$GEMSTONE_STONE_DIR"
        echo "::set-output name=topazini-path::$GEMSTONE_STONE_DIR/.topazini"
        export SUPERDOIT_ROOT=${{ steps.downloadSuperDoitProject.outputs.superDoit-root }}
        export GEMSTONE_SYSTEM_CONF=$GEMSTONE_STONE_DIR/system.conf
        echo "::set-output name=stone-system-conf-path::$GEMSTONE_SYSTEM_CONF"
        ${{ github.action_path }}/.github/actions/setupAndStartStone.sh
      shell: bash
