name: "CI"
on:
  pull_request:
    branches:
      - v1
  push:

jobs:
  self-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        gemstone: [ 3.6.0, 3.6.1 ]
    name: ${{ matrix.gemstone }} ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - uses: ./
      with:
        gemstone-version: ${{matrix.gemstone}}
        superDoit-branch: 'issue_21'
    - run: |
        simple.solo -h
        simple.solo
        versionReport.solo

