name: "CI"
on: [push, pull_request]
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@main
   - run: npm ci
   - run: npm test

  # test action works running from the graph
  self-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@main
    - uses: dalehenrich/setup-superDoit@main
      with:
        gemstone-version: '3.6.0'
        superDoit-branch: 'issue_21'
    - run: |
        which simple.solo
        ls /home/runner/.superDoit/gemstone/gs
        simple.solo -h

