name: "CI"
on:
  pull_request:
    branches:
      - v1
  push:
  schedule:
    - cron: "15 2 25 * *" #run job on the 25th day of every month on the 15th minute of the 2nd hour

jobs:
  self-test:
    runs-on: ${{ matrix.os }}
    env:
       PLATFORM: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        gemstone: [ 3.6.0, 3.6.1 ]
    name: ${{ matrix.gemstone }} ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - uses: ./
      with:
        gemstone-version: ${{matrix.gemstone}}
        superDoit-branch: 'issue_21'
    - run: |
        simple.solo -h
        simple.solo
        versionReport.solo
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - self-test
    runs-on: ubuntu-18.04
    steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
         with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
          name: 'action run' 
