name: "CI"
on: [push, pull_request]

jobs:
  self-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@master
    - uses: dalehenrich/setup-superDoit@main
      with:
        gemstone-version: '3.6.0'
        superDoit-branch: 'issue_21'
    - run: |
        which simple.solo
        ls /home/runner/.superDoit/gemstone/gs
        simple.solo -h

