name: "CI"
on:
  pull_request:
    branches:
      - v1
      - v2
  push:
  schedule:
    - cron: "15 2 25 * *" #run job on the 25th day of every month on the 15th minute of the 2nd hour

jobs:
  self-test:
    runs-on: ${{ matrix.os }}
    env:
       PLATFORM: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ ubuntu-18.04, macos-10.15 ]
        # gemstone: [ 3.6.1, 3.6.0, 3.5.7 ]
        os: [ macos-10.15 ]
        gemstone: [ 3.5.7 ]
    name: ${{ matrix.gemstone }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: downloadSuperDoit
        uses: ./
        with:
          gemstone-version: ${{matrix.gemstone}}
          superDoit-branch: 'v2.0.0-issue_24'
      - run: echo product-directory ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
      - run: echo gemstone-product-name ${{ steps.downloadSuperDoit.outputs.gemstone-product-name }}
      - run: echo gemstone-product-version ${{ steps.downloadSuperDoit.outputs.gemstone-version }}
      - run: echo solo-product-name ${{ steps.downloadSuperDoit.outputs.solo-product-name }}
      - run: echo solo-extent-version ${{ steps.downloadSuperDoit.outputs.solo-extent-version }}
      # download GemSTone product trees for mac 
      - name: download_gemstone_for_mac
        if: ${{ matrix.os == 'macos-10.15' }}
        run: |
          cd ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
          downloadGemStone.sh ${{ matrix.gemstone }}
      # download GemStone product trees for mac when matrix.gemstone does not support topaz solo
      - name: download_solo_gemstone_for_mac
        if: ${{ (matrix.os == 'macos-10.15') && (matrix.gemstone != steps.downloadSuperDoit.outputs.solo-extent-version) }}
        run: |
          cd ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
          downloadGemStone.sh ${{ steps.downloadSuperDoit.outputs.solo-extent-version }}
      - run: ls -l ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
      # setup shared memory on mac
      - name: setup_shared_memory_for_mac
        if: ${{ matrix.os == 'macos-10.15' }}
        run: |
          # macos-10.15 needs to have shared memory and semaphores installed to run a stone
          setSharedMemory.sh
      # create symbolic link for mac solo scripts to product tree
      - name: create_solo_symbolic_link_for_mac
        if: ${{ (matrix.os == 'macos-10.15') }}
        run: |
          cd ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}
          ln -s ${{steps.downloadSuperDoit.outputs.gemstone-product-directory}}/${{ steps.downloadSuperDoit.outputs.solo-product-name }} ../solo/product
      - run: ls -l ${{ steps.downloadSuperDoit.outputs.gemstone-product-directory }}/../solo
      - run: |
          canUSeeMe.solo -h
          canUSeeMe.solo
          versionReport.solo
#  slack-workflow-status:
#    if: always()
#    name: Post Workflow Status To Slack
#    needs:
#      - self-test
#    runs-on: ubuntu-18.04
#    steps:
#       - name: Slack Workflow Notification
#         uses: Gamesight/slack-workflow-status@master
#         with:
#          repo_token: ${{secrets.GITHUB_TOKEN}}
#          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
#          name: 'action run' 
