name: "CI"
on:
  pull_request:
    branches:
      - v1
      - v2
  push:
  schedule:
    - cron: "15 2 25 * *" #run job on the 25th day of every month on the 15th minute of the 2nd hour

jobs:
  self-test:
    runs-on: ${{ matrix.os }}
    env:
       PLATFORM: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ ubuntu-18.04, macos-10.15 ]
        # gemstone: [ 3.6.1, 3.6.0, 3.5.7 ]
        os: [ ubuntu-18.04 ]
        gemstone: [ 3.6.1 ]
    name: ${{ matrix.gemstone }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-superDoit
        uses: ./
        with:
          gemstone-version: ${{matrix.gemstone}}
          superDoit-branch: 'v2.0.0-issue_24'
      - name: validate_solo_setup
        run: |
          var=${{ steps.setup-superDoit.inputs.superDoit-branch }}
          echo "superDoit-branch = $var"
          var=${{ steps.setup-superDoit.outputs.gemstone-version }}
          echo "gemstone-version = $var"
          simple.solo -h
          simple.solo
          versionReport.solo
#  slack-workflow-status:
#    if: always()
#    name: Post Workflow Status To Slack
#    needs:
#      - self-test
#    runs-on: ubuntu-18.04
#    steps:
#       - name: Slack Workflow Notification
#         uses: Gamesight/slack-workflow-status@master
#         with:
#          repo_token: ${{secrets.GITHUB_TOKEN}}
#          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
#          name: 'action run' 
